# To set up this env run:
# conda env create -f conda_env.yml
# conda activate two_tower_env
# misc/gpu_test.py can be run to test the env can find the GPU


name: two_tower_env
channels:
  - pytorch
  - nvidia
  - defaults # must come after pytorch and nvidia
dependencies:
  - python=3.10         
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - jupyterlab           
  - pytorch              
  - pytorch-cuda=11.8    # Change cuda version to match the model of GPU
