version: '3.8'

services:
  twotower-app:
    build: .
    ports:
      - "8888:8888"
    environment:
      - PYTHONPATH=/app
    volumes:
      # Mount data directory if you want to persist/update models
      - ./data:/app/data:ro
      - ./artifacts:/app/artifacts:ro
      - ./frontend/chroma_store:/app/frontend/chroma_store
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 300s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G 