program: sweep_train.py
method: random
metric:
  goal: minimize
  name: best_val_loss
# Alternative metric options (uncomment to use):
# metric:
#   goal: maximize
#   name: val_accuracy
# metric:
#   goal: maximize  
#   name: val_similarity_gap
parameters:
  LR:
    values: [0.001]
  BATCH_SIZE:
    values: [64]
  EPOCHS:
    values: [5]
  HIDDEN_DIM:
    values: [128]
  MARGIN:
    values: [0.3]
  RNN_TYPE:
    values: ["GRU"]
  NUM_LAYERS:
    values: [2]
  DROPOUT:
    values: [0]
  LOSS_TYPE:
    values: ["triplet"]
  SUBSAMPLE_RATIO:
    values: [0.1]
early_terminate:
  type: hyperband
  min_iter: 1
  max_iter: 5