program: sweep_train.py
method: random
metric:
  goal: minimize
  name: best_val_loss
# Alternative metric options (uncomment to use):
# metric:
#   goal: maximize
#   name: val_accuracy
# metric:
#   goal: maximize  
#   name: val_similarity_gap
parameters:
  LR:
    values: [0,005, 0.001]
  BATCH_SIZE:
    values: [256, 512]
  EPOCHS:
    values: [1]
  HIDDEN_DIM:
    values: [64, 128, 256]
  MARGIN:
    values: [0.1, 0.3, 0.5]
  RNN_TYPE:
    values: ["GRU", "LSTM"]
  NUM_LAYERS:
    values: [1, 2, 3]
  DROPOUT:
    values: [0.0, 0.1]
  LOSS_TYPE:
    values: ["triplet"]
  SUBSAMPLE_RATIO:
    values: [0.05]
  SHARED_ENCODER:
    values: [false, true]
early_terminate:
  type: hyperband
  min_iter: 1
  max_iter: 5