program: sweep_train.py
method: random
metric:
  goal: minimize
  name: best_val_loss
# Alternative metric options (uncomment to use):
# metric:
#   goal: maximize
#   name: val_accuracy
# metric:
#   goal: maximize  
#   name: val_similarity_gap
parameters:
  LR:
    values: [0.0001, 0.0005, 0.001, 0.002]
  BATCH_SIZE:
    values: [32, 64, 128]
  EPOCHS:
    values: [3, 5]
  HIDDEN_DIM:
    values: [32, 64, 128, 256]
  MARGIN:
    values: [0.2, 0.5, 1.0]
  RNN_TYPE:
    values: ["GRU", "LSTM"]
  NUM_LAYERS:
    values: [1, 2, 3]
  DROPOUT:
    values: [0.0, 0.1, 0.2, 0.3]
  LOSS_TYPE:
    values: ["triplet"]
  SUBSAMPLE_RATIO:
    values: [0.01, 0.02, 0.05]
  SHARED_ENCODER:
    values: [false, true]
early_terminate:
  type: hyperband
  min_iter: 1
  max_iter: 5