program: sweep_train.py
method: random
metric:
  goal: minimize
  name: best_val_loss
# Alternative metric options (uncomment to use):
# metric:
#   goal: maximize
#   name: best_val_triplet_accuracy
# metric:
#   goal: maximize  
#   name: best_val_similarity_gap
parameters:
  LR:
    values: [0.0001, 0.0005, 0.001]
  BATCH_SIZE:
    values: [16, 32, 64]
  EPOCHS:
    values: [5]
  HIDDEN_DIM:
    values: [32, 64, 128]
  MARGIN:
    values: [0.2, 0.5]
  RNN_TYPE:
    values: ["GRU"]
  NUM_LAYERS:
    values: [1, 2]
  DROPOUT:
    values: [0.1, 0.3]
  LOSS_TYPE:
    values: ["triplet"]
  GRADIENT_ACCUMULATION_STEPS:
    values: [2, 4]
  SUBSAMPLE_RATIO:
    values: [0.01]
early_terminate:
  type: hyperband
  min_iter: 2